const pages=[...document.querySelectorAll('.page')],nav=[...document.querySelectorAll('.nav')],form=document.querySelector('#form'),steps=[...document.querySelectorAll('.form-step')],nodes=[...document.querySelectorAll('.step')];let current=0;
const copy=[['Inserisci il volo','Bastano i dati essenziali per iniziare.'],['Descrivi il disservizio','Indica che cosa è successo al tuo viaggio.'],['I tuoi contatti','La verifica è avviata: indicaci dove ricevere l’esito.'],['Documenti','Puoi aggiungerli ora oppure in seguito.']];
function showPage(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.page===id));scrollTo({top:0,behavior:'smooth'})}
function render(){steps.forEach((s,i)=>s.classList.toggle('active',i===current));nodes.forEach((n,i)=>{n.classList.toggle('active',i===current);n.classList.toggle('done',i<current);n.querySelector('i').textContent=i<current?'✓':i+1});document.querySelector('#step-title').textContent=copy[current][0];document.querySelector('#step-desc').textContent=copy[current][1];document.querySelector('#step-num').textContent=current+1;document.querySelector('#prev').style.visibility=current===0?'hidden':'visible';document.querySelector('#next').textContent=current===steps.length-1?'Verifica idoneità →':'Continua →'}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>{current=0;form.reset();render();showPage('wizard')}));
function validationMessage(el){if(el.validity.valueMissing)return 'Questo campo è obbligatorio';if(el.name==='volo'&&el.validity.patternMismatch)return 'Inserisci un numero volo valido, ad esempio AZ316';if(el.name==='telefono'&&el.validity.patternMismatch)return 'Inserisci un numero di telefono valido';if(el.type==='email'&&el.validity.typeMismatch)return 'Inserisci un indirizzo email valido';return 'Inserisci un valore valido'}
function validate(){let ok=true;steps[current].querySelectorAll('[required]').forEach(el=>{const valid=el.checkValidity();el.closest('label').classList.toggle('invalid',!valid);const msg=el.parentElement.querySelector('em');if(msg)msg.textContent=valid?'':validationMessage(el);if(!valid)ok=false});return ok}
function runFlightCheck(){const panel=document.querySelector('#verification');form.hidden=true;panel.hidden=false;setTimeout(()=>{panel.hidden=true;form.hidden=false;current=1;render()},2200)}
document.querySelector('#next').addEventListener('click',()=>{if(!validate())return;if(current===0){runFlightCheck();return}if(current<steps.length-1){current++;render()}else showPage('result')});
document.querySelector('#prev').addEventListener('click',()=>{if(current>0){current--;render()}});
form.addEventListener('input',e=>{if(e.target.name==='volo')e.target.value=e.target.value.toUpperCase().replace(/\s+/g,'');if(e.target.matches('input,select')){e.target.closest('label')?.classList.remove('invalid');const msg=e.target.parentElement.querySelector('em');if(msg)msg.textContent=''}});
document.querySelectorAll('.drop').forEach(box=>{const input=box.querySelector('input'),btn=box.querySelector('button'),name=box.querySelector('.file');const showFiles=files=>{if(files.length){name.textContent=files.length>1?`${files.length} file selezionati`:files[0].name;box.classList.add('uploaded')}};btn.addEventListener('click',e=>{e.stopPropagation();input.click()});box.addEventListener('click',()=>input.click());['dragenter','dragover'].forEach(ev=>box.addEventListener(ev,e=>{e.preventDefault();box.classList.add('drag')}));['dragleave','drop'].forEach(ev=>box.addEventListener(ev,e=>{e.preventDefault();box.classList.remove('drag')}));box.addEventListener('drop',e=>showFiles(e.dataTransfer.files));input.addEventListener('change',()=>showFiles(input.files))});
document.querySelector('#submit').addEventListener('click',()=>{const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)});
const search=document.querySelector('#search'),filter=document.querySelector('#filter'),rows=[...document.querySelectorAll('#rows tr')];function filterRows(){const q=search.value.toLowerCase(),f=filter.value;rows.forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)&&(!f||r.querySelector('.status').textContent.trim()===f)?'':'none')}search.addEventListener('input',filterRows);filter.addEventListener('change',filterRows);render();
