const pages=[...document.querySelectorAll('.page')], nav=[...document.querySelectorAll('.nav')];
function showPage(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.page===id));scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>{current=0;render();showPage('wizard')}));
const steps=[...document.querySelectorAll('.form-step')], nodes=[...document.querySelectorAll('.step')], form=document.querySelector('#form');let current=0,timer;
const copy=[['I tuoi dati','Iniziamo dalle informazioni per ricontattarti.'],['Dettagli del volo','Raccontaci cosa è successo durante il viaggio.'],['Documentazione','Aggiungi i documenti utili alla verifica.'],['Analisi AI','Elaborazione della valutazione preliminare.']];
function render(){steps.forEach((s,i)=>s.classList.toggle('active',i===current));nodes.forEach((n,i)=>{n.classList.toggle('active',i===current);n.classList.toggle('done',i<current);n.querySelector('i').textContent=i<current?'✓':i+1});document.querySelector('#step-title').textContent=copy[current][0];document.querySelector('#step-desc').textContent=copy[current][1];document.querySelector('#step-num').textContent=current+1;document.querySelector('#prev').style.visibility=current===0?'hidden':'visible';document.querySelector('#next').style.display=current===3?'none':'block';if(current===3)runAnalysis()}
function validate(){let ok=true;steps[current].querySelectorAll('[required]').forEach(el=>{let valid=el.checkValidity();el.closest('label').classList.toggle('invalid',!valid);el.nextElementSibling.textContent=valid?'':'Inserisci un valore valido';if(!valid)ok=false});return ok}
document.querySelector('#next').addEventListener('click',()=>{if(current<2&&!validate())return;if(current<3){current++;render()}});document.querySelector('#prev').addEventListener('click',()=>{if(current>0){clearInterval(timer);current--;render()}});
form.addEventListener('input',e=>{if(e.target.matches('input,select')){e.target.closest('label')?.classList.remove('invalid');if(e.target.nextElementSibling)e.target.nextElementSibling.textContent=''}});
document.querySelectorAll('.drop').forEach(box=>{const input=box.querySelector('input'),btn=box.querySelector('button'),name=box.querySelector('.file');btn.addEventListener('click',()=>input.click());box.addEventListener('click',e=>{if(!e.target.matches('button'))input.click()});['dragenter','dragover'].forEach(ev=>box.addEventListener(ev,e=>{e.preventDefault();box.classList.add('drag')}));['dragleave','drop'].forEach(ev=>box.addEventListener(ev,e=>{e.preventDefault();box.classList.remove('drag')}));box.addEventListener('drop',e=>{const files=e.dataTransfer.files;if(files.length){name.textContent=files.length>1?`${files.length} file selezionati`:files[0].name;box.classList.add('uploaded')}});input.addEventListener('change',()=>{if(input.files.length){name.textContent=input.files.length>1?`${input.files.length} file selezionati`:input.files[0].name;box.classList.add('uploaded')}})});
function runAnalysis(){clearInterval(timer);let value=0;const bar=document.querySelector('#bar'),pct=document.querySelector('#pct'),items=[...document.querySelectorAll('.analysis-list>div')];bar.style.width='0';pct.textContent='0%';items.forEach(x=>{x.classList.remove('done');x.querySelector('i').textContent='○'});timer=setInterval(()=>{value+=2;bar.style.width=value+'%';pct.textContent=value+'%';items.forEach((x,i)=>{if(value>=(i+1)*30){x.classList.add('done');x.querySelector('i').textContent='✓'}});if(value>=100){clearInterval(timer);setTimeout(()=>showPage('result'),500)}},55)}
document.querySelector('#submit').addEventListener('click',()=>{const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)});
const search=document.querySelector('#search'),filter=document.querySelector('#filter'),rows=[...document.querySelectorAll('#rows tr')];function filterRows(){const q=search.value.toLowerCase(),f=filter.value;rows.forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)&&(!f||r.querySelector('.status').textContent.trim()===f)?'':'none')}search.addEventListener('input',filterRows);filter.addEventListener('change',filterRows);render();
